// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG90WBqr_rNRvzuwsllPJiQ5zCqMU1Lyw',
    appId: '1:143474015125:web:07c81d00185b39976e549c',
    messagingSenderId: '143474015125',
    projectId: 'civil-tempo-414911',
    authDomain: 'civil-tempo-414911.firebaseapp.com',
    storageBucket: 'civil-tempo-414911.firebasestorage.app',
    measurementId: 'G-96V55W14EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7zwofWCCd---dG9LOL1QKDkvnrxMBCJ0',
    appId: '1:143474015125:android:10d4bec569ff1cf96e549c',
    messagingSenderId: '143474015125',
    projectId: 'civil-tempo-414911',
    storageBucket: 'civil-tempo-414911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ssrG7kjMTwapWGK7RW7j6qjR2Cg4SaE',
    appId: '1:143474015125:ios:0073045df246b8b06e549c',
    messagingSenderId: '143474015125',
    projectId: 'civil-tempo-414911',
    storageBucket: 'civil-tempo-414911.firebasestorage.app',
    iosBundleId: 'com.phd.exam.flutterFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ssrG7kjMTwapWGK7RW7j6qjR2Cg4SaE',
    appId: '1:143474015125:ios:71f7156a98ba7f0a6e549c',
    messagingSenderId: '143474015125',
    projectId: 'civil-tempo-414911',
    storageBucket: 'civil-tempo-414911.firebasestorage.app',
    iosBundleId: 'com.phd.exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG90WBqr_rNRvzuwsllPJiQ5zCqMU1Lyw',
    appId: '1:143474015125:web:f61ffef6ad713caf6e549c',
    messagingSenderId: '143474015125',
    projectId: 'civil-tempo-414911',
    authDomain: 'civil-tempo-414911.firebaseapp.com',
    storageBucket: 'civil-tempo-414911.firebasestorage.app',
    measurementId: 'G-LNEH2D5ZX3',
  );
}
